name: Build project

on: push
jobs: 
  build:
    name: Build app
    runs-on: ubuntu-latest
    steps:
      - name: Pull repo
        uses: actions/checkout@v2
      - name: print current dir
        run: pwd
      - name: print list of files
        run: ls
      - name: check dotnet
        run: dotnet build
      - name: check npm
        run: npm -v
      - name: print list of files ofter build
        run: ls .\ThoughtsListener.Api\ -R


        